export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD'
export const FETCH_ROBOTS_REQUEST = 'FETCH_ROBOTS_REQUEST'
export const FETCH_ROBOTS_SUCCESS = 'FETCH_ROBOTS_SUCCESS'
export const FETCH_ROBOTS_FAILURE = 'FETCH_ROBOTS_FAILURE'
